version: '3'
services:
  api:
    build:
      context: ./board-api
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./board-api:/board-api
      - /board-api/node_modules
    networks:
      - board-network
  board:
    build:
      context: ./board
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./board:/board
      - /board/node_modules
    depends_on:
      - api
    networks:
      - board-network
networks:
  board-network:
    driver: bridge
