version: '3'
services:
  api:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./packages/server:/packages/server
      - ./packages/server/node_modules
    networks:
      - board-network
  board:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./packages/client:/packages/client
      - ./packages/client/node_modules
    depends_on:
      - api
    networks:
      - board-network
networks:
  board-network:
    driver: bridge
