version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - board-network
  board:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - api
    networks:
      - board-network
networks:
  board-network:
    driver: bridge
